[project]
name = "tasks4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.7.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.0",
]
